### ISSUE TITLE
TypeError: Parameter.make_metavar() missing 1 required positional argument: 'ctx' with Python 3.13 and Typer

### ISSUE THREAD

**Issue by chenrui333** [oguzhan-yilmaz/balcony#56]
seeing some issue with 0.3.3 release build with click 8.2+
```
balcony --help

 Usage: balcony [OPTIONS] COMMAND [ARGS]...

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/balcony/0.3.3/bin/balcony", line 8, in <module>
    sys.exit(run_app())
             ~~~~~~~^^
  File "/opt/homebrew/Cellar/balcony/0.3.3/libexec/lib/python3.13/site-packages/balcony/cli.py", line 682, in run_app
    app(prog_name="balcony")
    ~~~^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/balcony/0.3.3/libexec/lib/python3.13/site-packages/typer/main.py", line 328, in __call__
    raise e
  File "/opt/homebrew/Cellar/balcony/0.3.3/libexec/lib/python3.13/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/balcony/0.3.3/libexec/lib/python3.13/site-packages/click/core.py", line 1442, in __call__
    return self.main(*args, **kwargs)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/balcony/0.3.3/libexec/lib/python3.13/site-packages/typer/core.py", line 778, in main
    return _main(
        self,
    ...<5 lines>...
        **extra,
    )
  File "/opt/homebrew/Cellar/balcony/0.3.3/libexec/lib/python3.13/site-packages/typer/core.py", line 215, in _main
    with self.make_context(prog_name, args, **extra) as ctx:
         ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/balcony/0.3.3/libexec/lib/python3.13/site-packages/click/core.py", line 1186, in make_context
    self.parse_args(ctx, args)
    ~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/opt/homebrew/Cellar/balcony/0.3.3/libexec/lib/python3.13/site-packages/click/core.py", line 1786, in parse_args
    rest = super().parse_args(ctx, args)
  File "/opt/homebrew/Cellar/balcony/0.3.3/libexec/lib/python3.13/site-packages/click/core.py", line 1197, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
                  ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/balcony/0.3.3/libexec/lib/python3.13/site-packages/click/core.py", line 2416, in handle_parse_result
    value = self.process_value(ctx, value)
  File "/opt/homebrew/Cellar/balcony/0.3.3/libexec/lib/python3.13/site-packages/click/core.py", line 2355, in process_value
    value = self.callback(ctx, self, value)
  File "/opt/homebrew/Cellar/balcony/0.3.3/libexec/lib/python3.13/site-packages/click/decorators.py", line 539, in show_help
    echo(ctx.get_help(), color=ctx.color)
         ~~~~~~~~~~~~^^
  File "/opt/homebrew/Cellar/balcony/0.3.3/libexec/lib/python3.13/site-packages/click/core.py", line 730, in get_help
    return self.command.get_help(self)
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/opt/homebrew/Cellar/balcony/0.3.3/libexec/lib/python3.13/site-packages/click/core.py", line 1064, in get_help
    self.format_help(ctx, formatter)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/balcony/0.3.3/libexec/lib/python3.13/site-packages/typer/core.py", line 791, in format_help
    return rich_utils.rich_format_help(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        obj=self,
        ^^^^^^^^^
        ctx=ctx,
        ^^^^^^^^
        markup_mode=self.rich_markup_mode,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/opt/homebrew/Cellar/balcony/0.3.3/libexec/lib/python3.13/site-packages/typer/rich_utils.py", line 606, in rich_format_help
    _print_options_panel(
    ~~~~~~~~~~~~~~~~~~~~^
        name=OPTIONS_PANEL_TITLE,
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
        console=console,
        ^^^^^^^^^^^^^^^^
    )
    ^
  File "/opt/homebrew/Cellar/balcony/0.3.3/libexec/lib/python3.13/site-packages/typer/rich_utils.py", line 369, in _print_options_panel
    metavar_str = param.make_metavar()
TypeError: Parameter.make_metavar() missing 1 required positional argument: 'ctx'
```
